import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Presente from '@/components/Presente';
import Porta from '@/components/Porta';

export default function Home() {
  return (
    <>
      <Head>
        <title>Loja Mayse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Presente />
        <div className={styles.portas}>
          <Porta />
          <Porta />
          <Porta />
          <Porta /> 
        </div>
      </main>
    </>
  );
}
