import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Porta from '@/components/Porta';
import {useState} from 'react'
import criarPortas, { atualizarPortas } from '@/functions/portas';

export default function Home() {

  const [portas, setPortas] = useState(criarPortas(3,1))



  function renderizarPortas() {
    return portas.map(porta =>
      <Porta 
      key={porta.numero} 
      value={porta} 
      onChange={novaPorta => {
        setPortas(atualizarPortas(portas, novaPorta))
      }
    }/>
)
  }

  return (
    <>
      <Head>
        <title>Loja Mayse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.portas}>
          {renderizarPortas()}
        </div>
      </main>
    </>
  );
}
