import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Presente from '@/components/Presente';
import Porta from '@/components/Porta';
import PortaModel from '@/models/porta';
import {useState} from 'react'

export default function Home() {
  const [p1, setP1] = useState(new PortaModel(1))
  return (
    <>
      <Head>
        <title>Loja Mayse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Presente />
        <div className={styles.portas}>
          <Porta value={p1} onChange={novaPorta => setP1(novaPorta)}/>
        </div>
      </main>
    </>
  );
}
